### ISSUE TITLE
^_^

### ISSUE THREAD

**Issue by Tayeb-Ali** [phr3nzy/ecommerce#1]
# hi bro  ,.
 ## This work is very very beautiful. :1st_place_medal: 
 ### I think it will be nicer after I get the Back-end :+1:  :package: 
 # lol  :lollipop:

**Comment by phr3nzy** [comment]
🤣🤣🤣🤣🤣

**Comment by phr3nzy** [comment]
The backend was supposed to be built using strapi, but i discarded that a long time ago. If you can build a backend for it, I can complete the frontend 🤣🤣🤷🏽

**Comment by Tayeb-Ali** [comment]
immmmmm
I will try

**Comment by phr3nzy** [comment]
Let me know if you need any help

**Comment by Tayeb-Ali** [comment]
OK i have Back-end for my Store App i well give you Rest-api and you build storefront website

**Comment by phr3nzy** [comment]
Alright, just waiting on you to finish. And, it's best if we communicate using telegram, here's my number +249121812240
